import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { page, escape as esc } from './layout.mjs';
import { projects } from './content.mjs';
const manifest = JSON.parse(readFileSync('dist/releases/manifest.json', 'utf8'));
const mb = bytes => `${(bytes / 1e6).toFixed(1)} MB`;
const save = (path, html) => { mkdirSync(`dist/${path}`, { recursive: true }); writeFileSync(`dist/${path}index.html`, html); };
const arrow = '<span aria-hidden="true">↗</span>';
const model = (p, eager = false, controls = false) => `<div class="model-view" data-model="${p.id}" role="img" aria-label="${p.id === 'pedal' ? 'Blender visualisation of the proposed VST pedal' : `Illustrative ${p.name} interface on a 3D phone`}"><img class="model-poster" src="/assets/3d/${p.id}.webp" alt="" width="940" height="1000" ${eager ? 'fetchpriority="high"' : 'loading="lazy"'} decoding="async"></div>${controls ? '<button class="motion-toggle art-motion-toggle" type="button" data-motion-toggle aria-pressed="false" aria-label="Pause animations" hidden>Pause motion</button>' : ''}`;
const cards = projects.map(p => `<a class="orbit-card project-${p.id}" href="/${p.id}/" data-project="${p.id}" data-name="${p.name}" aria-label="${p.name}: ${p.id === 'pedal' ? 'explore the hardware concept' : 'explore and download'}"><span class="orbit-card-art"><span class="orbit-card-kind">${p.number} / ${p.id === 'pedal' ? 'HARDWARE CONCEPT' : 'ANDROID APP'}</span><img src="/assets/3d/${p.id}.webp" alt="" width="940" height="1000" decoding="async"><span class="orbit-card-name">${p.name}<span aria-hidden="true">↗</span></span></span></a>`).join('\n');
const downloadRows = manifest.releases.map(app => {
 const p = projects.find(p => p.id === app.id);
 return `<article class="download-row" id="download-${app.id}"><a class="download-identity" href="/${app.id}/"><span class="row-number">${p.number}</span><img src="/assets/${p.icon}" alt="" width="40" height="40"><h3>${app.name}</h3></a><span class="download-version">v${app.version} <span>· ${mb(app.bytes)}</span></span><a class="download-link" href="${esc(app.url)}" aria-label="Download ${app.name} APK, ${mb(app.bytes)}">Download APK <span aria-hidden="true">↓</span></a><p>${app.id === 'revisen' ? 'A test server is required. ' : ''}<a href="/${app.id}/#test-build">Setup notes</a><span> / Android ${app.minAndroid}+</span></p></article>`;
}).join('');
save('', page({title: 'Kokonut — Independent software & hardware experiments', description: 'Explore the Kokonut orbit: SideQuest, Haste, Revisen and a live VST pedal concept. Independent apps and hardware experiments.', bodyClass: 'home', body: `<main id="main">
<section class="orbit-section" id="products" aria-label="Products"><span id="work"></span><span id="apps"></span>
<div class="orbit-topline wrap"><p>Independent software.<br>A few things in the works.</p><div class="orbit-top-actions"><span class="orbit-edition">SELECTED PRODUCTS</span><button class="orbit-autoplay" type="button" data-orbit-autoplay aria-pressed="false" aria-label="Pause automatic rotation" title="Pause automatic rotation" hidden><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M8 6v12M16 6v12"/></svg></button></div></div>
<div class="orbit-stage" data-orbit tabindex="0" role="region" aria-roledescription="carousel" aria-label="Four products around the Kokonut icon. Drag horizontally or use left and right arrow keys. Select a card to open its product page." aria-describedby="orbit-help"><h1 class="sr-only">Kokonut — Software & hardware experiments</h1><div class="orbit-brand" aria-hidden="true"><img src="/favicon.svg" alt="" width="180" height="180"></div><div class="orbit-links">${cards}</div></div><p class="sr-only" id="orbit-help">Select a product card to learn more. Drag horizontally or use the left and right arrow keys to choose a product. The small pause button stops automatic rotation.</p></section>
<section class="studio-section" id="about"><div class="wrap studio-grid"><p class="eyebrow">ABOUT ME</p><div><h2>Built one idea<br>at a time.</h2><div class="studio-copy"><p>Kokonut is where I build software and try out hardware ideas. Right now, I’m working on three Android apps: making plans with friends, keeping a food journal, and finding your way through difficult coursework.</p><p>Then there’s the pedal. A hardware experiment to take Windows VST plug-ins from a DAW to a live guitar rig. Still an idea, with a lot to figure out.</p></div><a class="studio-source" href="https://github.com/Tydooloo/kokonut" target="_blank" rel="noopener noreferrer">Find me on GitHub ${arrow}</a></div></div></section>
<section class="downloads-section wrap" id="downloads"><div class="section-heading"><p class="eyebrow">TRY THE APPS</p><h2>The download shelf.</h2><p class="section-note" data-device-notice>Free Android test builds. Read the setup notes before installing.</p></div><div class="download-list">${downloadRows}<article class="download-row concept-row"><a class="download-identity" href="/pedal/"><span class="row-number">04</span><h3>VST Pedal</h3></a><span class="download-version">Hardware concept</span><a class="download-link" href="/pedal/">Explore the idea ${arrow}</a><p>No prototype or download yet.</p></article></div><a class="quiet-link" href="/releases/">All release details & checksums ${arrow}</a></section>
<section class="install-section wrap" id="install"><div><p class="eyebrow">A QUICK NOTE</p><h2>First time with an APK?</h2><p>These are Android test builds. They won’t install on an iPhone or iPad.</p></div><div class="install-questions"><details><summary>How do I install an app?<span aria-hidden="true">+</span></summary><div><p>Read the app’s setup notes, then download its APK. Open the file from Downloads. Android may ask you to allow installation from your browser or Files. Follow the device’s guidance, install the app, and turn off the source permission afterwards.</p></div></details><details><summary>Android won’t install the file<span aria-hidden="true">+</span></summary><div><p>Check the minimum Android version and available storage. Re-download if the file is incomplete. Managed devices and protection settings can restrict installation. Keep Play Protect enabled and follow <a href="https://support.google.com/android/answer/9457058?hl=en" target="_blank" rel="noopener noreferrer">Android’s installation guidance</a>.</p></div></details><details><summary>I have an older test build<span aria-hidden="true">+</span></summary><div><p>A compatible build normally installs as an update. A different signing certificate may prevent that. Back up or export your data before removing an app: uninstalling can erase local food logs, files and settings.</p></div></details></div></section></main>`}));
for (const app of manifest.releases) {
 const p = projects.find(p => p.id === app.id);
 save(`${p.id}/`, page({title: `${p.name} — ${p.headline} — Kokonut`, description: p.description, path: `${p.id}/`, bodyClass: `project-page project-${p.id}`, body: `<main id="main"><div class="wrap"><nav class="breadcrumb" aria-label="Breadcrumb"><a href="/#work">All projects</a><span aria-hidden="true">/</span><span aria-current="page">${p.name}</span></nav>
<section class="project-hero"><div class="project-hero-copy"><p class="eyebrow">${p.number} / ${p.kind.toUpperCase()}</p><div class="app-name"><img src="/assets/${p.icon}" width="42" height="42" alt="">${p.name}</div><h1>${p.headline}</h1><p class="project-description">${p.description}</p><a class="button button-dark" href="#test-build">Get the Android build <span aria-hidden="true">↓</span></a><span class="hero-build-note">Free to try · ${app.id === 'revisen' ? 'Test server required' : 'Early access'}</span></div><div class="project-hero-art">${model(p, true, true)}<span class="model-note">ILLUSTRATIVE INTERFACE / 3D STUDY</span></div></section>
<section class="features-section" aria-label="What you can do">${p.features.map(([title, description], i) => `<article><span class="eyebrow">0${i + 1}</span><h2>${title}</h2><p>${description}</p></article>`).join('')}</section>
<section class="app-test-build" id="test-build"><div class="test-build-copy"><p class="eyebrow">YOURS TO TRY / ANDROID</p><h2>${p.firstTitle}</h2><p>${p.first}</p><p class="app-caveat">${p.caveat}</p></div><div class="app-download-panel"><span class="build-badge">${app.id === 'revisen' ? 'BACKEND SETUP REQUIRED' : 'ANDROID TEST BUILD'}</span><h3>${app.name}<span> ${app.version}</span></h3><dl><div><dt>File size</dt><dd>${mb(app.bytes)}</dd></div><div><dt>Requires</dt><dd>Android ${app.minAndroid}+</dd></div><div><dt>Published</dt><dd>${app.id === 'haste' ? '24' : '17'} Sep 2026</dd></div></dl><a class="button button-dark" href="${esc(app.url)}" aria-label="Download ${p.name} APK, ${mb(app.bytes)}">Download APK <span aria-hidden="true">↓</span></a><a class="quiet-link" href="/releases/#${app.id}">Test notes & checksum ${arrow}</a><a class="quiet-link" href="/#install">How to install</a><p class="platform-note" data-device-notice>For Android phones and tablets. APKs do not install on iPhone or iPad.</p></div></section>
<nav class="more-projects" aria-label="More projects"><span class="eyebrow">KEEP EXPLORING</span>${projects.filter(q => q.id !== p.id).map(q => `<a href="/${q.id}/">${q.name} ${arrow}</a>`).join('')}</nav></div></main>`}));
}
const pedal = projects[3];
save('pedal/', page({title: 'VST Pedal — A hardware concept by Kokonut', description: pedal.description, path: 'pedal/', bodyClass: 'project-page project-pedal', body: `<main id="main"><div class="wrap"><nav class="breadcrumb" aria-label="Breadcrumb"><a href="/#work">All projects</a><span aria-hidden="true">/</span><span aria-current="page">VST Pedal</span></nav><section class="project-hero"><div class="project-hero-copy"><p class="eyebrow">04 / HARDWARE CONCEPT</p><span class="app-name">VST Pedal</span><h1>Off the desk.<br>On the floor.</h1><p class="project-description">${pedal.description}</p><a class="button button-dark" href="#concept">Inside the idea ${arrow}</a><span class="hero-build-note">Concept only · No prototype or download yet</span></div><div class="project-hero-art">${model(pedal, true, true)}<span class="model-note">CONCEPT VISUALISATION / NOT A FINISHED PRODUCT</span></div></section>
<section class="concept-story" id="concept"><p class="eyebrow">THE QUESTION</p><h2>Why should your<br>sound stay at home?</h2><div><p>DAWs put a world of guitar effects within reach. Taking those exact sounds to a live show often means bringing a computer along, too.</p><p>The idea is a guitar pedal that runs Windows VST plug-ins itself: a physical home for a software signal chain, built around the way you play.</p><p class="concept-status">This is an early concept. Hardware, plug-in compatibility, latency, controls and release plans are still to be worked out. The model shows a possible direction, not a working prototype.</p></div></section>
<section class="features-section" aria-label="Questions to explore"><article><span class="eyebrow">01 / THE SOUND</span><h2>Your existing plug-ins.</h2><p>Explore whether familiar Windows VST effects can live in a dedicated pedal format.</p></article><article><span class="eyebrow">02 / THE FEEL</span><h2>Made for the floor.</h2><p>Find the right balance of tactile controls, a footswitch, and a readable live interface.</p></article><article><span class="eyebrow">03 / THE CHALLENGE</span><h2>Ready for a real stage.</h2><p>Investigate audio latency, reliability and plug-in hosting before promising a product.</p></article></section><nav class="more-projects" aria-label="More projects"><span class="eyebrow">MEANWHILE, TRY THE APPS</span>${projects.slice(0,3).map(p => `<a href="/${p.id}/">${p.name} ${arrow}</a>`).join('')}</nav></div></main>`}));
const entries = manifest.releases.map(app => `<article class="release-entry" id="${app.id}"><div class="release-title"><h2>${app.name}</h2><a href="/${app.id}/">About the app ${arrow}</a></div><p class="release-note">${esc(app.notes)}</p><dl class="release-facts"><dt>Version</dt><dd>${app.version} (build ${app.versionCode}) · ${app.buildType === 'release' ? 'Signed test build' : 'Development test build'}</dd><dt>Published</dt><dd>${app.id === 'haste' ? '24' : '17'} September 2026</dd><dt>Download</dt><dd>${mb(app.bytes)} · ${app.bytes.toLocaleString('en-NZ')} bytes</dd><dt>Requires</dt><dd>Android ${app.minAndroid}+ · ARM64, ARMv7 or x86-64</dd><dt>Package</dt><dd>${app.packageName}</dd></dl><div class="release-actions"><a class="button button-dark" href="${esc(app.url)}" aria-label="Download ${app.name} APK, ${mb(app.bytes)}">Download ${app.name} <span aria-hidden="true">↓</span></a><a href="/#install">Installation guide</a></div><details><summary>Verify this download <span aria-hidden="true">+</span></summary><div class="checksum-content"><p>The SHA-256 checksum identifies this exact file. The APK’s Android signing certificate was verified before upload.</p><code class="checksum">${app.sha256}</code><button class="copy-button" type="button" data-copy="${app.sha256}" aria-live="polite">Copy SHA-256</button><p>Signing certificate SHA-256</p><code class="checksum">${app.certificateSha256}</code></div></details></article>`).join('');
save('releases/', page({title: 'Downloads & release notes — Kokonut', description: 'Download SideQuest, Haste and Revisen Android test builds. Read setup requirements and verify file checksums.', path: 'releases/', body: `<main class="prose wrap" id="main"><p class="eyebrow">THE DOWNLOAD SHELF</p><h1>Ready when<br>you are.</h1><p class="prose-lead" data-device-notice>Three apps. Free Android test builds. Pick one, read the notes, and make it yours.</p><p>These APKs are for Android phones and tablets. They are not Google Play releases and cannot be installed on iPhone or iPad. Installing a newer build does not guarantee compatibility with saved test data.</p>${entries}<aside class="release-concept"><span class="eyebrow">04 / STILL AN IDEA</span><h2>Looking for the pedal?</h2><p>The VST Pedal is a hardware concept. There is no prototype or download available yet.</p><a href="/pedal/">Explore the concept ${arrow}</a></aside><h2>About the files</h2><p>APKs are public GitHub Release assets. A GitHub account is not required. All three files passed Android signature verification before their original publication. Their recorded sizes and hashes identify those files; they do not verify every app feature or every phone.</p><p><a href="${manifest.releaseUrl}">SideQuest & Revisen release</a> · <a href="https://github.com/Tydooloo/kokonut/releases/tag/haste-1.0.0-test-2026-09-24">Haste release</a> · <a href="/releases/manifest.json">Release manifest</a></p></main>`}));
save('privacy/', page({title: 'Website privacy — Kokonut', description: 'How the Kokonut website handles visitor information and Android download links.', path: 'privacy/', body: `<main class="prose wrap" id="main"><p class="eyebrow">WEBSITE PRIVACY</p><h1>A little clarity.</h1><p>This page covers the Kokonut website. It does not replace privacy information for SideQuest, Haste or Revisen, which have their own accounts, storage and services.</p><h2>Browsing the website</h2><p>The website code does not use analytics, advertising trackers, sign-up forms, cookies or local storage. It does not request your location, camera, microphone or contacts. Motion preferences last for the current page visit only.</p><p>Hosting and network providers may process ordinary technical request information, including IP addresses, requested URLs and browser information, to serve and protect the site. Fonts, 3D models, scripts and images are served with the website.</p><h2>Downloading an app</h2><p>APK download buttons lead to public files hosted by GitHub. GitHub processes the request under its own privacy terms. Downloading a file does not create an app account. When you open an app, its own permissions and data handling apply.</p><h2>Your device</h2><p>The website checks your browser’s device information locally to display installation guidance for iPhone and iPad visitors. That check is not sent to an analytics service. Copy buttons write to the clipboard only when you press them. Interactive 3D is optional: the project artwork and links also work without it.</p><p><a href="/">Return to the collection</a> · <a href="/releases/">App test notes</a></p></main>`}));
writeFileSync('dist/404.html', page({title: 'Page not found — Kokonut', description: 'That page has wandered off. Return to the Kokonut project collection.', body: `<main class="prose wrap not-found" id="main"><p class="eyebrow">404 / A SMALL DETOUR</p><h1>This one<br>wandered off.</h1><p>The page may have moved. There are still a few good things to explore.</p><a class="button button-dark" href="/">Back to the collection ${arrow}</a></main>`}));
writeFileSync('dist/sitemap.xml', `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${['', ...projects.map(p=>p.id+'/'), 'releases/', 'privacy/'].map(path => `<url><loc>https://kokonut.cc/${path}</loc></url>`).join('')}</urlset>\n`);
console.log('Built eight pages from shared content and the unchanged Android release manifest.');
