export const projects = [
  { id: 'sidequest', name: 'SideQuest', number: '01', kind: 'Android app', category: 'Make a little more of life.', icon: 'sidequest-icon.png', headline: 'More out there.',
    description: 'For the plans that finally make it out of the group chat. Find your next adventure, bring your people, and keep the good bits.',
    features: [['Find your next thing', 'Browse activities by cost, time and group size. Save a favourite for later.'], ['Make the plan', 'Poll a date, collect RSVPs, and keep your schedule and group chat together.'], ['Keep the good bits', 'Save photos, videos and inside jokes in your private group.']],
    firstTitle: 'Bring your people.', first: 'Sign in with Google or email, then create a private group or join one with an invite. Head to Discover for activity ideas and turn one into a plan.',
    caveat: 'SideQuest uses hosted services for accounts, group data and media. It needs an internet connection. Current notifications are inside the app; these test builds are still being refined.' },
  { id: 'haste', name: 'Haste', number: '02', kind: 'Android app', category: 'Less food admin. More living.', icon: 'haste-icon.svg', headline: 'Eat. Log. Live.',
    description: 'A food journal that leaves room for real life. Start with a photo, a few words, or the details you already know.',
    features: [['Start with what you know', 'Use a photo, voice or text. Enter known nutrition manually when you have it.'], ['Have the final say', 'Review portions and assumptions before saving. With AI connected, adjust and re-estimate.'], ['See your days together', 'Browse daily logs, edit meals and repeat favourites. Food logs stay on your device.']],
    firstTitle: 'Start with one meal.', first: 'Use the local explore flow to try manual food entry, then review and save a meal. Sign in for hosted food search and optional AI estimates.',
    caveat: 'AI estimates can be inaccurate and are subject to daily limits. Explore entries can be temporary, and local food logs do not automatically transfer to another phone.' },
  { id: 'revisen', name: 'Revisen', number: '03', kind: 'Android pilot', category: 'Find your “I get it” moment.', icon: 'revisen-icon.png', headline: 'Make it click.',
    description: 'A place for the questions you got wrong, the working you want to keep, and the practice that helps it all make sense.',
    features: [['Keep the question', 'Capture a problem from text, a screenshot or your camera. Keep your working alongside it.'], ['Connect it to your course', 'Add course materials, review suggested passages, and confirm the links that help.'], ['Practise the next step', 'Get checked practice for supported maths and motion questions. Self-mark other questions and revisit when due.']],
    firstTitle: 'Connect, then get curious.', first: 'Get a reachable Revisen server URL from your test organiser and enter it in Connection settings. You can then create an account or explore the server’s sample workspace.',
    caveat: 'This is a server-dependent pilot. Without a reachable backend, the learning workspace will not work. Optional AI transcription and explanations need a configured Gemini service; they do not establish mastery or grade all question types.' },
  { id: 'pedal', name: 'VST Pedal', number: '04', kind: 'Hardware concept', category: 'Your plug-ins. On stage.', headline: 'Off the desk. On the floor.',
    description: 'What if your favourite Windows VST plug-ins could come to the gig? An idea for a standalone guitar pedal that brings a DAW’s sounds into a live rig.' },
];
